### ISSUE TITLE
Unable to open SQLite file on different directory

### ISSUE THREAD

**Issue by subdan** [GetBreeze/breeze-db#10]
When I call DB.setup I point to a SQLite file:
```
DB.setup(function (error:Error):void
{
	if (error == null)
	{
		callback();
	}
	else
	{
		trace(error);
	}
}, File.applicationStorageDirectory.resolvePath("data"+File.separator+"db.sqlite"));
```
On Android devide I get this error:
`SQLError: 'Error #3125: Unable to open the database file.', details:'Connection closed.', operation:'open', detailID:'1001'`

**Comment by marpies** [comment]
You will likely need to create the `data` directory first. If it doesn't exist, AIR will not be able to create the `db.sqlite` file.

```as3
var dir:File = File.applicationStorageDirectory.resolvePath("data");
if(!dir.exists)
{
    dir.createDirectory();
}

DB.setup( ... , dir.resolvePath("db.sqlite") );
```

**Comment by subdan** [comment]
Thanks
