### ISSUE TITLE
query.first doesn't work

### ISSUE THREAD

**Issue by subdan** [GetBreeze/breeze-db#14]
I have a Child Class
```
public class Child extends BreezeModel
{
	public var id:int;
	public var name:String;
	
	public function Child()
	{
		_tableName = "children";
	}
	
	public static function get query():BreezeModelQueryBuilder
	{
		return new BreezeModelQueryBuilder(Child);
	}
}
```
I want to get first Child of children Table. I run this code:
```
Child.query.first(function (error:Error, child:Child):void {
	trace(error, child);
});
```
The callback doesn't fire if there is not a first Child. Why?
Expected behaviour:
In output I want to see "null, null" if there is no first Child in children table.

**Comment by marpies** [comment]
I can't reproduce this, `null` and `null` is returned if the table is empty.

Can you try adding the `super()` call to your model's constructor?

```as3
public class Child extends BreezeModel
{
	...

	public function Child()
	{
		super()   // <----
		_tableName = "children";
	}

	...
}
```

**Comment by subdan** [comment]
Great! It works. Thank you!
