### ISSUE TITLE
Unable to set encryption key as ByteArray

### ISSUE THREAD

**Issue by subdan** [GetBreeze/breeze-db#16]
DB.encryptionKey is a setter that accepts only a String.
But [in the documentation ](https://www.getbreeze.io/breeze-db/database/#encryption)this setter also accepts ByteArray:
```
// Write 16 bytes
var key:ByteArray = new ByteArray();
for(var i:int = 0; i < 16; ++i)
{
    key.writeByte(i);
}

DB.encryptionKey = key;
```

Could you change setter argument type from :String to :* ?

**Comment by marpies** [comment]
Thanks for reporting.
