### ISSUE TITLE
SQLStatement optimisation?

### ISSUE THREAD

**Issue by chichilatte** [GetBreeze/breeze-db#2]
Hi sorry for all these questions! I'm curious to know if Breeze does any reusing of `SQLStatement` instances. Specifically I'm thinking of when the `text` is the same but `parameters` are different, to avoid AIR having to re-parse the sql. Something along the lines of...

https://github.com/probertson/air-sqlite/blob/master/src/com/probertson/data/sqlRunnerClasses/StatementCache.as

**Comment by marpies** [comment]
The statements are not cached right now. Thanks for the tip, we'll consider adding it in the future.

**Comment by ecornbower** [comment]
@marpies I wonder how much benefit reusing ```SQLStatement``` objects would even have. Seems like the code would be more complicated and error-prone while not adding much of a performance boost. I would not think that SQL parsing is a significant source of query time.

**Comment by chichilatte** [comment]
Good point. I would add that it could be really simple, e.g. reusing the most recent statement only – once a SQLStatement has completed, store it (with `parameters` set to null) in the BreezeDb instance and try to reuse it any time you want to create a new SQLStatement. 

For things like batch-inserts this might be a good optimisation.

**Comment by marpies** [comment]
@chichilatte 
I tested batch-inserts to research this feature, but I didn't see any significant decrease in query execution times. As @kcornbower pointed out, parsing the query is likely not that demanding.
