### ISSUE TITLE
Unable to open DB

### ISSUE THREAD

**Issue by subdan** [GetBreeze/breeze-db#8]
In my app I want to import and export SQLite file to transfer it between devices. I've found an issue when trying to open imported SQLite file:

If I use encryption I get this error:
SQLError: 'Error #3125: Unable to open the database file.', details:'An encryption key cannot be specified when the database is not encrypted.', operation:'open', detailID:'1011'

If I don't use encryption I get this error:
SQLError: 'Error #3138: File opened is not a database file.', details:'', operation:'open'

If I open imported SQLite file in ADL emulator I don't get these errors.

**Comment by subdan** [comment]
I use https://github.com/tuarua/Zip-ANE to compress and uncompress DB file. I tried to do not compress sqlite file and now it works.

**Comment by marpies** [comment]
It seems the compression/decompression process corrupts the encryption. Probably not a lot we can do about this.

**Comment by subdan** [comment]
Ok. I will try to use another zip lib.
