### ISSUE TITLE
Unable to change SQLite file location

### ISSUE THREAD

**Issue by subdan** [GetBreeze/breeze-db#9]
When I try to change SQLite file location
DB.file = File.documentsDirectory;
I get error:
Property file is read-only.

**Comment by marpies** [comment]
You cannot change the file location after the database has been setup. If you need to do that then you will need to copy the database file manually and then use the new file path in the next `setup` call.

**Comment by subdan** [comment]
I tried to change DB.file property before calling DB.setup but DB class doesn't have a setter for file.

**Comment by subdan** [comment]
BreezeDbInstance doesn't have setter for file, only getter

> public function get file():File
> {
> 			return _file;
> }

**Comment by marpies** [comment]
It's not meant to be used in this way. The `DB.file` property is there only to tell you where the database file is located. The only way to specify where the file is created is by setting the location in the `setup` method and updating `BreezeDb.storageDirectory`

**Comment by subdan** [comment]
![screenshot_1](https://user-images.githubusercontent.com/410293/41972723-fca4a772-7a12-11e8-854a-2701131aca0b.png)

**Comment by subdan** [comment]
Update the documentation.

**Comment by marpies** [comment]
Ok thanks!
